In [1]:
from tensorflow.keras.preprocessing.text import one_hot

In [2]:
### sentences
sent=[  'the glass of milk',
     'the glass of juice',
     'the cup of tea',
    'I am a good boy',
     'I am a good developer',
     'understand the meaning of words',
     'your videos are good',]

In [3]:
sent

['the glass of milk',
 'the glass of juice',
 'the cup of tea',
 'I am a good boy',
 'I am a good developer',
 'understand the meaning of words',
 'your videos are good']

In [4]:
## Define the vocabulary size
voc_size=10000

In [5]:
sent

['the glass of milk',
 'the glass of juice',
 'the cup of tea',
 'I am a good boy',
 'I am a good developer',
 'understand the meaning of words',
 'your videos are good']

In [6]:
### One Hot Representation
## the below output is the index at which for the word 1 would be present
## we need to use this in out embedding layer later, so we wont be using that sparse matrix ones and zeroes thing, 
## instead we will try to convert all our words based on the below index
one_hot_repr=[one_hot(words,voc_size)for words in sent]
one_hot_repr

[[1536, 7817, 6945, 3117],
 [1536, 7817, 6945, 6807],
 [1536, 2046, 6945, 7173],
 [1336, 5800, 3505, 9426, 3744],
 [1336, 5800, 3505, 9426, 4338],
 [4191, 1536, 6420, 6945, 3302],
 [744, 4991, 4440, 9426]]

In [7]:
## word Embedding Representation

from tensorflow.keras.layers import Embedding
#from tensorflow.keras.processing.sequence import pad_sequences
from tensorflow.keras.utils import pad_sequences
from tensorflow.keras.models import Sequential

In [8]:
import numpy as np

In [9]:
sent_length=8
embedded_docs=pad_sequences(one_hot_repr,padding='pre',maxlen=sent_length)
print(embedded_docs)

[[   0    0    0    0 1536 7817 6945 3117]
 [   0    0    0    0 1536 7817 6945 6807]
 [   0    0    0    0 1536 2046 6945 7173]
 [   0    0    0 1336 5800 3505 9426 3744]
 [   0    0    0 1336 5800 3505 9426 4338]
 [   0    0    0 4191 1536 6420 6945 3302]
 [   0    0    0    0  744 4991 4440 9426]]


In [10]:
## feature representation
dim=10

In [11]:
model=Sequential()
model.add(Embedding(voc_size,dim,input_length=sent_length))
model.compile('adam','mse')

In [12]:
model.summary()

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 embedding (Embedding)       (None, 8, 10)             100000    
                                                                 
Total params: 100000 (390.62 KB)
Trainable params: 100000 (390.62 KB)
Non-trainable params: 0 (0.00 Byte)
_________________________________________________________________


In [13]:
model.predict(embedded_docs)

1/1 [==============================] - 0s 62ms/step


array([[[-0.02361053,  0.04197523,  0.0409718 , -0.04984181,
          0.00224547, -0.0448794 , -0.01795701, -0.03771507,
          0.01111053,  0.03640982],
        [-0.02361053,  0.04197523,  0.0409718 , -0.04984181,
          0.00224547, -0.0448794 , -0.01795701, -0.03771507,
          0.01111053,  0.03640982],
        [-0.02361053,  0.04197523,  0.0409718 , -0.04984181,
          0.00224547, -0.0448794 , -0.01795701, -0.03771507,
          0.01111053,  0.03640982],
        [-0.02361053,  0.04197523,  0.0409718 , -0.04984181,
          0.00224547, -0.0448794 , -0.01795701, -0.03771507,
          0.01111053,  0.03640982],
        [-0.01299056,  0.0447173 ,  0.02889803,  0.04411313,
         -0.04707436,  0.03046067, -0.04184661, -0.04354974,
          0.00010322, -0.00065335],
        [-0.02206677, -0.01403437, -0.04569428, -0.03366344,
         -0.02162953, -0.01705412,  0.03623186, -0.0314235 ,
         -0.04922214,  0.02010586],
        [ 0.01990608, -0.02390113, -0.03681886,  0.0

In [19]:
embedded_docs[0]

array([   0,    0,    0,    0, 1536, 7817, 6945, 3117])

In [15]:
model.predict(embedded_docs[0])

1/1 [==============================] - 0s 31ms/step


array([[-0.02361053,  0.04197523,  0.0409718 , -0.04984181,  0.00224547,
        -0.0448794 , -0.01795701, -0.03771507,  0.01111053,  0.03640982],
       [-0.02361053,  0.04197523,  0.0409718 , -0.04984181,  0.00224547,
        -0.0448794 , -0.01795701, -0.03771507,  0.01111053,  0.03640982],
       [-0.02361053,  0.04197523,  0.0409718 , -0.04984181,  0.00224547,
        -0.0448794 , -0.01795701, -0.03771507,  0.01111053,  0.03640982],
       [-0.02361053,  0.04197523,  0.0409718 , -0.04984181,  0.00224547,
        -0.0448794 , -0.01795701, -0.03771507,  0.01111053,  0.03640982],
       [-0.01299056,  0.0447173 ,  0.02889803,  0.04411313, -0.04707436,
         0.03046067, -0.04184661, -0.04354974,  0.00010322, -0.00065335],
       [-0.02206677, -0.01403437, -0.04569428, -0.03366344, -0.02162953,
        -0.01705412,  0.03623186, -0.0314235 , -0.04922214,  0.02010586],
       [ 0.01990608, -0.02390113, -0.03681886,  0.03274127, -0.00357101,
         0.03333323, -0.03277668,  0.02166199